org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.249
loader_version_range=[1,)

mod_id=info_tab
mod_name=Info TAB
mod_license=MIT
mod_framework=neoforge
mod_version=0.0.0-beta.1
mod_group_id=com.skd.infotab
